# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fd5bbd3fdb92b9a08b08962481e2c072257a4e087d3e82233079296828385b475c4651266fc23ba619512f0c5a34b8b6686034ffa30e339b988d798ff194086

test:
  secret_key_base: 17c8e07e24747232a529b6e526a27ac6bb9345f8a9c86f6a72d36fbd181a9cb2861a89611561a948a381dd9f3607008a5c35a09bc4d886e78d873e6342501198

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
