# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(title: "Science fiction", description: "")
Category.create(title: "Satire", description: "")
Category.create(title: "Drama", description: "")
Category.create(title: "Action and Adventure", description: "")
Category.create(title: "Romance", description: "")
Category.create(title: "Mystery", description: "")
Category.create(title: "Horror", description: "")
Category.create(title: "Self help", description: "")
Category.create(title: "Health", description: "")
Category.create(title: "Guide", description: "")
Category.create(title: "Travel", description: "")
Category.create(title: "Children's", description: "")
Category.create(title: "Religion, Spirituality & New Age", description: "")
Category.create(title: "Science", description: "")
Category.create(title: "History", description: "")
Category.create(title: "Math", description: "")
Category.create(title: "Anthology", description: "")
Category.create(title: "Poetry", description: "")
Category.create(title: "Encyclopedias", description: "")
Category.create(title: "Dictionaries", description: "")
Category.create(title: "Comics", description: "")
Category.create(title: "Art", description: "")
Category.create(title: "Cookbooks", description: "")
Category.create(title: "Diaries", description: "")
Category.create(title: "Journals", description: "")
Category.create(title: "Prayer books", description: "")
Category.create(title: "Series", description: "")
Category.create(title: "Trilogy", description: "")
Category.create(title: "Biographies", description: "")
Category.create(title: "Autobiographies", description: "")
Category.create(title: "Fantasy", description: "")